name: oxipng

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

concurrency:
  # If we ever end up with two concurrent CI jobs for the same commit, the former should be cancelled
  group: ci-${{ github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    name: CI

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    # Prevent tags and in-repo PRs from triggering this workflow more than once for a commit
    if: github.ref_type != 'tag' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin

        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            target-apt-arch: amd64
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            target-apt-arch: amd64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            target-apt-arch: arm64
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
            target-apt-arch: arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-15
          - target: aarch64-apple-darwin
            os: macos-15

    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install musl development files
        if: endsWith(matrix.target, '-musl')
        env:
          APT_ARCH: ${{ matrix.target-apt-arch }}
        run: |
          sudo apt-get -yq update
          sudo apt-get -yq install musl-tools "musl-dev:$APT_ARCH"

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: nightly-2026-08-25
          target: ${{ env.CARGO_BUILD_TARGET }}
          components: rust-src # Required by -Zbuild-std
          cache-bin: false
          cache-shared-key: cache

      - name: Install nextest
        uses: taiki-e/install-action@82cd3e7658a6f96c86c0234aeeda1748937cb0a1 # v2.85.13
        with:
          tool: nextest

      - name: Run tests
        run: |
          cargo nextest run --release --features sanity-checks
          cargo test --doc --release --features sanity-checks

      - name: Build benchmarks
        run: cargo bench --no-run

      - name: Build CLI binary
        run: cargo build --release -Zbuild-std
        env:
          RUSTFLAGS: "-Zlocation-detail=none -Zunstable-options -Cpanic=immediate-abort"

      - name: Upload CLI binary as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Oxipng binary (${{ matrix.target }})
          path: |
            target/${{ env.CARGO_BUILD_TARGET }}/release/oxipng
            target/${{ env.CARGO_BUILD_TARGET }}/release/oxipng.exe
          compression-level: 9
