name: test

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

concurrency:
  # If we ever end up with two concurrent test jobs for the same commit, the former should be cancelled
  group: test-${{ github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Test (${{ matrix.toolchain }})

    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Prevent tags and in-repo PRs from triggering this workflow more than once for a commit
    if: github.ref_type != 'tag' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork)

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - 1.88.0 # MSRV, keep in sync with rust-version in Cargo.toml

    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: ${{ matrix.toolchain }}
          cache-bin: false
          cache-shared-key: cache

      - name: Install nextest
        uses: taiki-e/install-action@82cd3e7658a6f96c86c0234aeeda1748937cb0a1 # v2.85.13
        with:
          tool: nextest

      - name: Run tests
        run: |
          cargo nextest run --release --features sanity-checks
          cargo test --doc --release --features sanity-checks
